CREATE TABLE Chats (
  id SERIAL PRIMARY KEY,
  user_id INT,
  texto_user TEXT NOT NULL,
  texto_llm TEXT NOT NULL,
  data_criacao TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);