CREATE TABLE  Users (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  senha VARCHAR(100) NOT NULL,
  data_criacao TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
